"""Shared pytest fixtures for oopsie_tools tests.

Session-scoped fixtures generate HDF5 + MP4 files once per test session into a
pytest-managed temporary directory and are cleaned up automatically at the end.

  tmp_path_factory  (session-scoped) – shared fixtures used across many tests
  tmp_path          (function-scoped, built-in) – per-test isolation

File generation delegates to the canonical fixture generators so that the
validator tests always exercise the exact same files as other test modules.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from oopsie_tools.test.fixtures.make_valid import (
    make_failure,
    make_multi_camera,
    make_success,
    make_unannotated,
    write_valid_episode,  # re-exported for per-test use in test modules
)
from oopsie_tools.test.fixtures.make_invalid import (
    _MAKERS_SIMPLE,
    _MAKERS_WITH_VIDEO,
    _write_video,
)

__all__ = ["write_valid_episode"]


# ---------------------------------------------------------------------------
# Session-scoped fixtures: valid episodes
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def valid_episode(tmp_path_factory) -> Path:
    """Fully valid oopsiedata_format_v1 unannotated episode."""
    d = tmp_path_factory.mktemp("valid")
    make_unannotated(d)
    return d / "episode_unannotated.h5"


@pytest.fixture(scope="session")
def valid_success_episode(tmp_path_factory) -> Path:
    """Valid episode annotated as success."""
    d = tmp_path_factory.mktemp("valid_success")
    make_success(d)
    return d / "episode_success.h5"


@pytest.fixture(scope="session")
def valid_failure_episode(tmp_path_factory) -> Path:
    """Valid episode annotated as failure."""
    d = tmp_path_factory.mktemp("valid_failure")
    make_failure(d)
    return d / "episode_failure.h5"


@pytest.fixture(scope="session")
def valid_session_dir(tmp_path_factory) -> Path:
    """Session directory containing all four valid episode types."""
    d = tmp_path_factory.mktemp("valid_session")
    make_unannotated(d)
    make_success(d)
    make_failure(d)
    make_multi_camera(d)
    return d


# ---------------------------------------------------------------------------
# Session-scoped fixture: invalid episodes
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def invalid_fixtures(tmp_path_factory) -> dict[str, Path]:
    """Dict mapping fixture stem → Path for every invalid HDF5 file.

    Generated by the same make_invalid module used for manual inspection,
    so tests and the generator stay in sync automatically.
    """
    d = tmp_path_factory.mktemp("invalid")

    for maker in _MAKERS_SIMPLE:
        maker(d)

    for maker in _MAKERS_WITH_VIDEO:
        maker(d, _write_video)

    return {p.stem: p for p in d.glob("invalid_*.h5")}
