# Any config related to the robot setup, observation, action will be stored here.


# ===============================
# ===== Robot Setup Related =====
# ===============================

policy_name: pi0.5
robot_name: franka_research_3
gripper_name: robotiq_2f_85
is_biarm: false
uses_mobile_base: false
control_freq: 10
camera_names:
  - left
  - right
  - wrist


# ===============================
# ===== Observation Related =====
# ===============================

# Observation keys. Options: "joint_position", "cartesian_position", "gripper_position", "base_position"
robot_state_keys:
  - joint_position
  - cartesian_position
  - gripper_position

# Required for knowing what each index in the robot_state["joint_position"] corresponds to
robot_state_joint_names:
  - base_joint
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6
  - wrist_joint

robot_state_orientation_representation: "euler_xyz" 


# ==========================
# ===== Action Related =====
# ==========================

action_space:
  - "joint_velocity"
  - "gripper_binary"


# If action space is joint velocity / joint position
action_joint_names:
  - base_joint
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6
  - wrist_joint 
