# Any config related to the robot setup, observation, action will be stored here.


# ===============================
# ===== Robot Setup Related =====
# ===============================

policy_name: # str (Rq) (Example: "pi0.5", "openvla", "diffusion_policy_custom" ...)
robot_name: # str (Required) (Example: "franka_panda", "franka_research_3", "ur5e", "yam_pro" ...)
gripper_name: # str (Required) (Example: "robotiq_2f_85", "robotiq_2f_140", "yam_gripper" ...)
is_biarm: # bool (Required)
uses_mobile_base: # bool (Required)
control_freq: # int (Required)
camera_names: # list of str (Required) (Example: ["left", "right", "wrist"])
  - # str


# ===============================
# ===== Observation Related =====
# ===============================

# Observation keys. Options: "joint_position" (Required), "gripper_position" (Required), "cartesian_position", "base_position"
robot_state_keys: # list of str
  - # str

# If cartesian_position is in the robot_state_keys, specify the orientation representation. Options:
# 1. "euler_{format}" (where format is "xyz", "xyx" ... (shape (3,))
# 2. "quat" (quaternion should be scalar last, shape (4,))
# 3. "matrix" (rotation matrix, shape (3, 3))
# 4. "rot6d" (first two columns of the rotation matrix, flattened, shape (6,). This is used by openpi)
# 5. "rotvec" (axis-angle, shape (3,))
robot_state_orientation_representation: # str


# ==========================
# ===== Action Related =====
# ==========================

# Action space (Required) 
# Options: "joint_velocity", "joint_position", "cartesian_position", "cartesian_velocity"
# Gripper options: "gripper_position", "gripper_velocity", "gripper_binary"
# Base options: "base_velocity", "base_position"
action_space: # list of str
  - # str


# If action space is cartesian position, specify the orientation representation. Options:
# 1. "euler_{format}" (where format is "xyz", "xyx" ... (shape (3,))
# 2. "quat" (quaternion should be scalar last, shape (4,))
# 3. "matrix" (rotation matrix, shape (3, 3))
# 4. "rot6d" (first two columns of the rotation matrix, flattened, shape (6,). This is used by openpi)
# 5. "rotvec" (axis-angle, shape (3,))
orientation_representation: # str


# ==========================
# ===== Optional Keys =====
# ==========================

# For knowing what each index in the robot_state["joint_position"] corresponds to
robot_state_joint_names: # list of str
  - # str


# For knowing what each index in the action["joint_position"] corresponds to
action_joint_names: # list of str
  - # str


# Options: "OSC", "joint_position", "joint_velocity"
controller: # str
gains:
  joint_position:
    kp: # list of float
    kd: # list of float

  joint_velocity:
    kv: # list of float

  osc:
    kp_pos: # list of float
    kd_pos: # list of float
    kp_ori: # list of float
    kd_ori: # list of float

intrinsic calibration matrix: 
  <str>: # camera name str
    - # 3 x list of three floats (camera intrinsics for left camera)

extrinsic calibration matrix:
  <str>: # camera name str
    - # 4 x list of four floats (camera extrinsics in the form of a transformation matrix)
# ========================  